### ISSUE TITLE
App is crashing when OnBackpress on demo app

### ISSUE THREAD

**Issue by l1068** [AperoVN/AperoModuleAds#4]
2021-09-07 19:37:19.399 25595-25595/com.demo.test E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.demo.test, PID: 25595
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object com.google.android.gms.ads.nativead.NativeAd.zza()' on a null object reference
        at com.google.android.gms.ads.nativead.NativeAdView.setNativeAd(com.google.android.gms:play-services-ads-lite@@20.2.0:1)
        at com.ads.control.Admod.populateUnifiedNativeAdView(Admod.java:1062)
        at com.ads.control.dialog.DialogExitApp1.initView(DialogExitApp1.java:78)
        at com.ads.control.dialog.DialogExitApp1.onCreate(DialogExitApp1.java:57)
        at android.app.Dialog.dispatchOnCreate(Dialog.java:421)
        at android.app.Dialog.show(Dialog.java:315)
        at com.demo.test.activity.MainActivity.showConfirmExitDialog(MainActivity.java:479)
        at com.demo.test.activity.MainActivity.onBackPressed(MainActivity.java:391)
        at android.app.Activity.onKeyUp(Activity.java:3644)
        at android.view.KeyEvent.dispatch(KeyEvent.java:2841)
        at android.app.Activity.dispatchKeyEvent(Activity.java:3961)
        at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:122)
        at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:84)
        at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:140)
        at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:599)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
        at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3068)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
        at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:367)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5411)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5279)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4786)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4839)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4805)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4945)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4813)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5002)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4786)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4839)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4805)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4813)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4786)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4839)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4805)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4978)
        at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:5139)
        at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3064)
        at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2607)
        at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2598)
        at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3041)
        at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:143)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:336)
        at android.os.Looper.loop(Looper.java:174)
        at android.app.ActivityThread.main(ActivityThread.java:7403)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

**Comment by l1068** [comment]
Để tái tạo lỗi, chỉ cần cài đặt ứng dụng demo và mở ứng dụng mà không cần kết nối internet khi bấm vào mặt sau, sự cố này sẽ xảy ra. hãy sửa chữa nó
